language: c++
os: linux
dist: xenial
git:
  depth: 1

env:
  global:
  - RUST_VERSION=1.40.0
  - CARGO_HOME=$TRAVIS_BUILD_DIR/third_party/rust_crates/
  - PATH=$CARGO_HOME/bin:$PATH

install:
- |-
  # Install Rust.
  if [ ! $(rustc --version | grep $RUST_VERSION) ]; then
    curl -sSf https://sh.rustup.rs | sh -s -- -y \
      --default-toolchain $RUST_VERSION
    rustup default $RUST_VERSION
  fi
  rustup component add clippy
  rustup component add rustfmt
  rustc --version
  cargo --version
  python --version

script:
- curl -fL https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/clang+llvm-8.0.1-x86_64-linux-sles11.3.tar.xz --output /tmp/clang.tar.xz
- tar xf /tmp/clang.tar.xz -C /tmp
- mv /tmp/clang+llvm-8.0.1-x86_64-linux-sles11.3 /tmp/clang-llvm
- ls -la /tmp/clang-llvm
- ls -la /tmp/clang-llvm/bin
- /tmp/clang-llvm/bin/clang --version
- CLANG_BASE_PATH=/tmp/clang-llvm/ cargo build -vv --release --locked --all-targets
- cargo test -vv --release --locked --all-targets
