language: c++
git:
  depth: 1

env:
  global:
  - RUST_VERSION=1.40.0
  - CARGO_HOME=$TRAVIS_BUILD_DIR/third_party/rust_crates/
  - PATH=$CARGO_HOME/bin:$PATH

matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      env:
        - LLVM_VER=llvm
    - os: osx
      osx_image: xcode11.3
      env:
        - LLVM_VER=llvm@8
    - os: osx
      osx_image: xcode11.3
      env:
        - LLVM_VER=llvm@7
    - os: osx
      osx_image: xcode11.3
      env:
        - LLVM_VER=llvm@6

install:
- |-
  # Install Rust.
  if [ ! $(rustc --version | grep $RUST_VERSION) ]; then
    curl -sSf https://sh.rustup.rs | sh -s -- -y \
      --default-toolchain $RUST_VERSION
    rustup default $RUST_VERSION
  fi
  rustup component add clippy
  rustup component add rustfmt
  rustc --version
  cargo --version
  python --version

script:
- brew update
- brew install $LLVM_VER
- CLANG_BASE_PATH=/usr/local/opt/$LLVM_VER/ cargo build -vv --release --locked --all-targets
- cargo test -vv --release --locked --all-targets
